In [5]:
from collections import Counter
a = Counter(c= 3,d= 4)
print(list(a.elements()))

['c', 'c', 'c', 'd', 'd', 'd', 'd']


In [11]:
a = 'please god save this world from corona'
b = Counter(a)
print(sorted(list(b.most_common(5))))

[(' ', 6), ('a', 3), ('e', 3), ('o', 5), ('s', 3)]


In [20]:
import re
a = ['asshole arse','ass ass','ass jackass']

for i in a:
    z = re.match("(a\w+)\W(j\w+)",i)
    if z:
        print((z.groups()))


('ass', 'jackass')


In [6]:
from collections import Counter 
import re
txt = "dont beg for somthing to someone.if u want it then u have to earn it.there is no shortcut.if u dont run fast  u will get a broken anda"
words = re.findall('\w+',txt)
print(sorted(Counter(words).most_common(10)))

[('beg', 1), ('dont', 2), ('for', 1), ('if', 2), ('it', 2), ('someone', 1), ('somthing', 1), ('to', 2), ('u', 4), ('want', 1)]


In [10]:
from collections import Counter,OrderedDict
class orderedCounter(Counter,OrderedDict):
    pass
word = []
n = int(input("enter the number :"))
print("Input the words :")

for i in range(n):
    word.append(input().strip())
word_ctr = orderedCounter(word)
print(len(word))

for words in word_ctr:
    print(word_ctr[words],end = ',')

enter the number :4
Input the words :
ass
tit
pussy
tit
4
1,2,1,

In [15]:
import collections
import re

n = int(input("number of subjects :"))
item_order= collections.OrderedDict()

for i in range(n):
    sub_name_list = re.split(r'(\d+)$',input('Input sub name and marks : ').strip())
    sub_name = sub_name_list[0]
    marks = int(sub_name_list[1])
    
    if sub_name not in item_order:
        item_order[sub_name] = marks
    else:
        item_order[sub_name] = item_order[sub_name] + marks
for i in item_order:
    print(i,str(item_order[i]))

number of subjects :3
Input sub name and marks : ass 38
Input sub name and marks : tit 34
Input sub name and marks : tit 35
ass  38
tit  69


In [24]:
import collections
deque_color = collections.deque(['red','black','white'])
print(deque_color)

print("\nadd from left :" )
deque_color.appendleft("yellow")
print(deque_color)
print("\nadd from right")
deque_color.append("green")
print(deque_color)
print("\nremove from left")
deque_color.popleft()
print(deque_color)
print("\nremove from right")
deque_color.pop()
print(deque_color)
print("\nreverse the deque")
deque_color.reverse()
print(deque_color)

deque(['red', 'black', 'white'])

add from left :
deque(['yellow', 'red', 'black', 'white'])

add from right
deque(['yellow', 'red', 'black', 'white', 'green'])

remove from left
deque(['red', 'black', 'white', 'green'])

remove from right
deque(['red', 'black', 'white'])

reverse the deque
deque(['white', 'black', 'red'])


In [26]:
import collections
even_num = (2,4,6,8)
even_deque = collections.deque(even_num)
print(even_deque)
new_num = (9,1,3,5)
even_deque.extend(new_num)
print(even_deque)

deque([2, 4, 6, 8])
deque([2, 4, 6, 8, 9, 1, 3, 5])


In [32]:
import collections
dq = collections.deque([1,2,3])
print(dq)
print("deleting all item :")
dq.clear()
print("length of dque %d"%(len(dq)))

deque([1, 2, 3])
deleting all item :
length of dque 0


In [34]:
a = (1,2,3,4,5)
dq1 = collections.deque(a)
print(dq1)
dq2 = dq1.copy()
print(dq2)
print("dq1 id",id(dq1))
print("dq2 id",id(dq2))

deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5])
dq1 id 1734986064776
dq2 id 1734986066232


In [52]:
import collections
c = [1,1,2,3,4,5,6,2,4,6,7,8,4,3,2,1]
x = collections.deque(c)
print(x)
print(x.count(1),x.count(3))
print(dict(Counter(x)))
print("before rotating the deque :",x)
print("after rotating")
x.rotate()
print(x)

deque([1, 1, 2, 3, 4, 5, 6, 2, 4, 6, 7, 8, 4, 3, 2, 1])
3 2
{1: 3, 2: 3, 3: 2, 4: 3, 5: 1, 6: 2, 7: 1, 8: 1}
before rotating the deque : deque([1, 1, 2, 3, 4, 5, 6, 2, 4, 6, 7, 8, 4, 3, 2, 1])
after rotating
deque([1, 1, 1, 2, 3, 4, 5, 6, 2, 4, 6, 7, 8, 4, 3, 2])


In [55]:
from collections import Counter
language = ['PHP', 'PHP', 'Python', 'PHP', 'Python', 'JS', 'Python', 'Python','PHP', 'Python']
print("Original list:")
print(language)
cnt = Counter(language)
print("\nMost common element of the said list:")
print(cnt.most_common(1)[0][0])
print(cnt.most_common(1)[0])
print(cnt.most_common(1))



Original list:
['PHP', 'PHP', 'Python', 'PHP', 'Python', 'JS', 'Python', 'Python', 'PHP', 'Python']

Most common element of the said list:
Python
('Python', 5)
[('Python', 5)]


## Heapq algorithm


In [57]:
import heapq as hq
l = [1,2,3,4,5,6,7,8,9]
print("original list :",l)
print(hq.nlargest(3,l))


original list : [1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7]


In [63]:
import heapq
li = [3,4,2,5,7,1]
heapq.heapify(li)
print(" heapfy list ",end = "")
print(list(li))

 heapfy list [1, 4, 2, 5, 7, 3]


In [72]:
l = [9,4,5,7,3,2,8]
heapq.heapify(l)
heapq.heappush(l,1)
print(l)


[1, 2, 5, 3, 4, 9, 8, 7]


In [75]:
import heapq as hq
li = [9,4,5,6,2,1]
print(hq.nsmallest(4,li))

[1, 2, 4, 5]


In [79]:
hq.heappush(li,10)
print(list(li))

[4, 4, 9, 4, 2, 1, 5, 6, 4, 10]


In [83]:
hq.heappop(li)
print(li)

[2, 4, 9, 4, 10, 1, 5, 6]


In [85]:
import heapq as hq

def heapsort(li):
    h = []
    for value in li:
        hq.heappush(h,value)
    return [hq.heappop(h) for i in range(len(h))]
print(heapsort([9,4,5,7,3,2,8]))

[2, 3, 4, 5, 7, 8, 9]


In [87]:
import heapq as hq
num_list = [12,3,4,11,33,45,6,7]
hq.heapify(num_list)
print(sorted(list(num_list)))
print("another way")
res = [hq.heappop(num_list) for i in range(len(num_list))]
print(res)

[3, 4, 6, 7, 11, 12, 33, 45]
another way
[3, 4, 6, 7, 11, 12, 33, 45]


In [88]:
li = [45,3,34,55,66,77,32]
k = 4
hq.heapify(li)
s = [hq.heappop(li) for i in range(len(li))]
q = sorted(list(s))
print(q[-4])

45


In [89]:
import heapq

class Solution(object):
    def find_Kth_Largest(self, nums, k):
        """
        :type nums: List[int]
        :type of k: int
        :return value type: int
        """
        h = []
        for e in nums:
            heapq.heappush(h,e)
        for i in range(k):
            e = heapq.heappop(h)
            if i == k - 1:
                return e

arr_nums = [12, 14, 9, 50, 61, 41]
s = Solution()
result = s.find_Kth_Largest(arr_nums, 3)
print("Third largest element:",result)
#result = s.find_Kth_Largest(arr_nums, 2)
#print("\nSecond largest element:",result)
#result = s.find_Kth_Largest(arr_nums, 5)
#print("\nFifth largest element:",result)


Third largest element: 14


In [94]:
arr_nums = [12, 14, 9, 50, 61, 41]
h = []
for e in arr_nums:
    heapq.heappush(h,e)
print(h)
for i in range(3):
    e = heapq.heappop(h)
    i ==3 - 1
print(e)

[9, 14, 12, 50, 61, 41]
14


In [10]:
import heapq
from pprint import pprint
item = [{'items':'tshirt','price':550},
       {'items':'jeans','price':1550},
       {'items':'watch','price':3000},
       {'items':'shoe','price':2000},
       {'items':'sun_glass','price':400}]
cheap = heapq.nsmallest(3,item,key= lambda s:s['price'])
expensive = heapq.nlargest(3,item,key = lambda s : s['price'])
print("original dataset\n",item)
print("\ncheap\n")
pprint(cheap)
print("\nexpensive\n")
pprint(expensive)

original dataset
 [{'items': 'tshirt', 'price': 550}, {'items': 'jeans', 'price': 1550}, {'items': 'watch', 'price': 3000}, {'items': 'shoe', 'price': 2000}, {'items': 'sun_glass', 'price': 400}]

cheap

[{'items': 'sun_glass', 'price': 400},
 {'items': 'tshirt', 'price': 550},
 {'items': 'jeans', 'price': 1550}]

expensive

[{'items': 'watch', 'price': 3000},
 {'items': 'shoe', 'price': 2000},
 {'items': 'jeans', 'price': 1550}]


In [13]:
import heapq
a = [23,42,45,22,56,87]
b = [55,2,434,56,66,78]
c= [99,89,65,88,55,34]
a = sorted(a)
b= sorted(b)
c = sorted(c)
d = heapq.merge(a,b,c)
print(list(d))

[2, 22, 23, 34, 42, 45, 55, 55, 56, 56, 65, 66, 78, 87, 88, 89, 99, 434]


In [24]:
import numpy as np 
a = np.random.randint(1,10,size = (3,4))
n = len(a[0])
q = [(a[0][0], 0, 0)]
print(a)
print("\n",q)

[[7 4 8 4]
 [3 2 8 8]
 [4 2 1 6]]

 [(7, 0, 0)]


In [30]:
from collections import Counter
import heapq
class Solution:
    def most_frequent(self,words,k):
        ctr = Counter(words)
        print(ctr)
        heap = [(-ctr[word],word) for word in ctr]
        heapq.heapify(heap)
        print(heap)
        return [heapq.heappop(heap)[-1] for _ in range(k)]
    
if __name__ == '__main__':
    
    words = ['a','b','c','ab','a','bc','a','b','c']
    k = 3
    s = Solution()
    print(s.most_frequent(words,k))


Counter({'a': 3, 'b': 2, 'c': 2, 'ab': 1, 'bc': 1})
[(-3, 'a'), (-2, 'b'), (-2, 'c'), (-1, 'ab'), (-1, 'bc')]
['a', 'b', 'c']


In [46]:
from collections import Counter 
import heapq

def rearranging_str(str1):
    ctr = Counter(str1)
    heap = [(-value,key) for key,value in ctr.items()]
    print(heap)
    heapq.heapify(heap)
    
    print(len(heap))
    
    ans = []
    while len(heap) >=2:
        x1,y1 = heapq.heappop(heap)
        x2,y2 = heapq.heappop(heap)
        
        ans.extend([y1,y2])
        print(ans)
        if x1+1:heapq.heappush(heap,(x1+1,y1))
        if x2+1:heapq.heappush(heap,(x2+1,y2))
    return "".join(ans)+(heap[0][1] if heap else"")
print(rearranging_str('abbc'))

[(-1, 'a'), (-2, 'b'), (-1, 'c')]
3
['b', 'a']
['b', 'a', 'b', 'c']
babc


In [59]:
import heapq
from collections import Counter

def word_rearng(s):
    ctr = Counter(s)
    heap = [(-value,key) for key,value in ctr.items()]
    heapq.heapify(heap)
    if(-heap[0][0])*2 > len(s) + 1:
        return "none"
        
    ans = []
    while len(heap) >=2 :
        x1,y1 = heapq.heappop(heap)
        x2,y2 = heapq.heappop(heap)
        ans.extend([y1,y2])
        if x1 + 1:heapq.heappush(heap,(x1+1,y1))
        if x2+1:heapq.heappush(heap,(x2+1,y2))
    return "".join(ans) + (heap[0][1] if heap else "")
print(word_rearng("aaabc"))
print(word_rearng("aaab"))

abaca
none


In [62]:
import heapq
max_heap = []
min_heap = []
def add_num(num):
    if not max_heap and not min_heap:
        heapq.heappush(min_heap,num)
        print(max_heap,min_heap)
print(add_num(1))

[] [1]
None


In [63]:
10>>2

2

In [65]:
10<<2
12>>2

3

In [70]:

vowels = "aeiou" 
for i in vowels:
    print(i,ord(i))

a 97
e 101
i 105
o 111
u 117
